export enum RouteNames {
	ROOT = "ROOT",
	HOME = "HOME",
	ERROR_INTERNAL_SERVER_ERROR = "ERROR_INTERNAL_SERVER_ERROR",
	ERROR_ACCESS_DENIED = "ERROR_ACCESS_DENIED",
	ERROR_PAGE_NOT_FOUND = "ERROR_PAGE_NOT_FOUND"
}
